### ISSUE TITLE
easyinstall number 8 (themes) problem on install

### ISSUE THREAD

**Issue by useronegit** [ohitstom/spicetify-easyinstall#33]
(8/12) Downloading 'official' themes...
Traceback (most recent call last):
  File "modules\screens.py", line 204, in shownCallback
    await core.install(
  File "modules\core.py", line 201, in install
    await utils.chunked_download(
  File "modules\utils.py", line 253, in chunked_download
    async with aiofiles.open(path, "wb") as f:
  File "aiofiles\base.py", line 78, in __aenter__
  File "aiofiles\threadpool\__init__.py", line 80, in _open
  File "qasync\__init__.py", line 149, in run
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Shadow\\spicetify-cli\\Themes.zip'

^^ SOMETHING WENT WRONG! ^^

**Comment by ohitstom** [comment]
Fixed in new update, you can install python 3.8.9 and use the source code instead if you'd like.
