### ISSUE TITLE
Response payload is not completed when installing Spicetify

### ISSUE THREAD

**Issue by eugene32155500** [ohitstom/spicetify-easyinstall#52]
I was trying to install Spicetify, and it gets stuck on downloading 'official' themes. 

First error: 
(9/14) Downloading 'official' themes...
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
OSError: [WinError 10038] An operation was attempted on something that is not a socket
N/A% - ??:?? [##############              ] Themes.zip              

and after the first one i got this error:
Traceback (most recent call last):
  File "modules\screens.py", line 244, in shownCallback
    await core.install(
  File "modules\core.py", line 263, in install
    await utils.simultaneous_chunked_download(
  File "modules\utils.py", line 238, in simultaneous_chunked_download
    await asyncio.gather(*tasks)
  File "modules\utils.py", line 199, in _fetch
    async for chunk in r.content.iter_any():
  File "aiohttp\streams.py", line 35, in __anext__
  File "aiohttp\streams.py", line 397, in readany
  File "aiohttp\streams.py", line 304, in _wait
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed

^^ SOMETHING WENT WRONG! ^^

**Comment by ohitstom** [comment]
potential duplicate of #51, you can try the stuff i pointed out there. based on the error it seems like github is rate limiting you.

**Comment by eugene32155500** [comment]
> potential duplicate of #51, you can try the stuff i pointed out there. based on the error it seems like github is rate limiting you.

alright thanks,i will try that,wil keep you updated

**Comment by ohitstom** [comment]
> > potential duplicate of #51, you can try the stuff i pointed out there. based on the error it seems like github is rate limiting you.
> 
> tried to update the addons, i got basically the same error
> Maybe github is rate limiting,but i think its a bug...I may be wrong tho
> 
> 
> 

did you try a vpn

**Comment by eugene32155500** [comment]
> potential duplicate of #51, you can try the stuff i pointed out there. based on the error it seems like github is rate limiting you.

its been some time since i tried to install spicetify,but still i cant install spicetify,can you pls fix?

**Comment by ohitstom** [comment]
> > potential duplicate of #51, you can try the stuff i pointed out there. based on the error it seems like github is rate limiting you.
> 
> its been some time since i tried to install spicetify,but still i cant install spicetify,can you pls fix?

I don't really work on this project anymore, try installing spicetify in the traditional method. this project was made before marketplace was mainstream so it's kinda pointless now!

**Comment by eugene32155500** [comment]
> > > potential duplicate of #51, you can try the stuff i pointed out there. based on the error it seems like github is rate limiting you.
> > 
> > 
> > its been some time since i tried to install spicetify,but still i cant install spicetify,can you pls fix?
> 
> I don't really work on this project anymore, try installing spicetify in the traditional method. this project was made before marketplace was mainstream so it's kinda pointless now!

Ah,okay...
