### ISSUE TITLE
I don't know coding, but just wanted to send this in. I'm unable to download spicetify properly, and always get stuck on this even with various restarts and reinstalls.

### ISSUE THREAD

**Issue by Zekryuu** [ohitstom/spicetify-easyinstall#53]
(8/12) Downloading 'official' themes...
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 162, in _call_connection_lost
OSError: [WinError 10038] An operation was attempted on something that is not a socket
N/A% - ??:?? [ ##############             ] Themes.zip

**Comment by ohitstom** [comment]
not sure, feel free to run update > addons!

**Comment by Zekryuu** [comment]
Seems like updating addons also caused problems.
(1/5) Wiping old addons...
Finished wiping old addons!

(2/5) Downloading 'official' addons...
0%   - 00:00 [                            ] Newest Official Addons.z
Traceback (most recent call last):
  File "modules\screens.py", line 838, in shownCallback
    await core.update_addons(shipped=slider.update_addons_confirm_screen.version.isChecked())
  File "modules\core.py", line 598, in update_addons
    await utils.simultaneous_chunked_download(
  File "modules\utils.py", line 238, in simultaneous_chunked_download
    await asyncio.gather(*tasks)
  File "modules\utils.py", line 199, in _fetch
    async for chunk in r.content.iter_any():
  File "aiohttp\streams.py", line 35, in __anext__
  File "aiohttp\streams.py", line 397, in readany
  File "aiohttp\streams.py", line 304, in _wait
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed


^^ SOMETHING WENT WRONG! ^^

**Comment by ohitstom** [comment]
have you tried a vpn maybe? is easyinstall being ran from your main os drive?

**Comment by Zekryuu** [comment]
I just tried a VPN and it's a no go. I use a single SSD, so yes.
 From my research the error might be caused by my corrupted OS.
